name: GitHub Actions
on:
  push:
    branches:
      - "main"
jobs:
  deploy-firebase-hosting:
    runs-on: ubuntu-22.04
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
          access_token_lifetime: 1200s
      - name: Build
        run: npm ci && npm run build
          # {任意のビルド処理などを記述}
      - name: Deploy Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --project={ar-videoviewer} --only=hosting